### ISSUE TITLE
Styles not working and Asset precompile fails 0.1.3

### ISSUE THREAD

**Issue by rhodee** [hecbuma/compass-bootstrap#6]
I am beginning a new Rails 3.1 project using compass 0.12.alpha.3. I installed it using the instructions found [here.](https://gist.github.com/1184843) I then followed the installation for compass-bootstrap. Two things are happening. In my development environment no styles are loaded and when I run asset:precompile --trace I get the following error:

```
rake aborted!
Undefined variable: "$baseline".
(in /home/rhodee/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/compass-bootstrap- 0.1.3/vendor/assets/stylesheets/compass-bootstrap/_forms.scss)
 /home/rhodee/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/compass-bootstrap-0.1.3/vendor/assets/stylesheets/compass-bootstrap/_forms.scss:10
..
..
..
```

Interestingly when I make the import statement a sprocket directive, the bootstrap styles work fine (although precompile aborts).

What is wrong?

**Comment by ericdfields** [comment]
Just noticing this now. I recently completed porting this to bootstrap 2.0. If you feel like checking: https://github.com/ericdfields/compass-bootstrap

I sent in a pull request too so hopefully this gets updated.
